### ISSUE TITLE
Unit test target not added to scheme's test action

### ISSUE THREAD

**Issue by shamanskyh** [pinterest/xchammer#140]
I have a unit test target in an XCHammer generated project. In the scheme that's created, I would expect the test target to be added to the scheme's test action's `Tests` section, but it is not.

In order to enable the `Product > Test` action in Xcode, I must manually go into the scheme editor, choose the "Test" action in the left hand pane, choose the "Info" tab, and add the UnitTest target to the `Tests` section manually.

**Comment by jerrymarino** [comment]
Hey @shamanskyh thanks so much for the report! I'm looking into this and hoping to have a resolution soon.

It isn't yet clear to me if this is an internal config issue: we're using the DSL to generate projects and there is a green test case for the test scheme action in XCHammer.
