### ISSUE TITLE
Aspect error messages are swallowed

### ISSUE THREAD

**Issue by jerrymarino** [pinterest/xchammer#157]
When I run XCHammer, I'm no longer seeing errors from the aspect invocation

**Comment by rahul-malik** [comment]
Possibly fixed by https://github.com/pinterest/xchammer/pull/134 ?

**Comment by jerrymarino** [comment]
I don't know if that fixes the entire issue @rahul-malik we should probably have integration tests around the error.

Note: for anyone curious to see mentioned errors until this is fixed, the workaround is to run any bazel commands that are printed to standard output on the CLI manually. Basically, just copy and paste that command and run it manually.
