### ISSUE TITLE
Support Bazel 0.25

### ISSUE THREAD

**Issue by jerrymarino** [pinterest/xchammer#162]
Add support for Bazel 0.25. This includes all changes, the largest being support for deprecated resource attributes.

**Comment by LeeWong** [comment]
Please add support for Bazel 0.25 and list out all rule versions

**Comment by jerrymarino** [comment]
@rahul-malik Good call ✅ Last time I looked the main issue was handling 24.1+ attributes. I'll have to double check but it seems like https://github.com/pinterest/xchammer/pull/171 may be hanging up on this as well.
