### ISSUE TITLE
Tulsi build failure (xcodebuild crash, using Xcode 10)

### ISSUE THREAD

**Issue by kastiglione** [pinterest/xchammer#36]
I ran `make workspace` and got a build failure in Tulsi, see the full log below. From Tulsi's checkout directory I tried `xcodebuild clean` and that too fails (same error message, but empty stack trace).

I realize this might not be XCHammer's error to own, but it does block workspace generation.

Error message:

> API VIOLATION: `rock_XPCObjectToNSDictionary` would have returned `nil` without an error set.

Erro stack:

```
2018-09-17 14:00:19.774 xcodebuild[83737:3283066] *** Assertion failure in NSDictionary * _Nullable rock_XPCObjectToNSDictionary(xpc_object_t  _Nonnull __strong, ROCKSessionManager * _Nullable __strong, NSError * _Nullable __autoreleasing * _Nullable)(), /BuildRoot/Library/Caches/com.apple.xbs/Sources/ROCKit/ROCKit-24/ROCKit/NSDictionary+ROCK.m:172
** INTERNAL ERROR: Uncaught exception **
Uncaught Exception: API VIOLATION: rock_XPCObjectToNSDictionary would have returned nil without an error set.
Stack:
  0   __exceptionPreprocess (in CoreFoundation)
  1   objc_exception_throw (in libobjc.A.dylib)
  2   +[NSException raise:format:arguments:] (in CoreFoundation)
  3   -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] (in Foundation)
  4   rock_XPCObjectToNSDictionary (in ROCKit)
  5   __50-[SimDeviceSet subscribeToNotificationsWithError:]_block_invoke (in CoreSimulator)
  6   xpc_array_apply (in libxpc.dylib)
  7   -[SimDeviceSet subscribeToNotificationsWithError:] (in CoreSimulator)
  8   __45-[SimServiceContext deviceSetWithPath:error:]_block_invoke (in CoreSimulator)
  9   _dispatch_client_callout (in libdispatch.dylib)
 10   _dispatch_queue_barrier_sync_invoke_and_complete (in libdispatch.dylib)
 11   -[SimServiceContext deviceSetWithPath:error:] (in CoreSimulator)
 12   -[SimServiceContext defaultDeviceSetWithError:] (in CoreSimulator)
 13   __42-[DVTiPhoneSimulatorLocator startLocating]_block_invoke_2 (in IDEiOSSupportCore)
 14   __DVTDispatchAsync_block_invoke (in DVTFoundation)
 15   _dispatch_call_block_and_release (in libdispatch.dylib)
 16   _dispatch_client_callout (in libdispatch.dylib)
 17   _dispatch_continuation_pop (in libdispatch.dylib)
 18   _dispatch_async_redirect_invoke (in libdispatch.dylib)
 19   _dispatch_root_queue_drain (in libdispatch.dylib)
 20   _dispatch_worker_thread3 (in libdispatch.dylib)
 21   _pthread_wqthread (in libsystem_pthread.dylib)
 22   start_wqthread (in libsystem_pthread.dylib)

zsh: abort      xcodebuild build -verbose -scheme TulsiApp -derivedDataPath  -project   
```

**Comment by kastiglione** [comment]
Related question: When and why does the [pinned version of Tulsi](https://github.com/pinterest/xchammer/blob/0ecd860fbe5f2d33b75b350f87a12a6dd5da79cf/Package.swift#L31-L33) change?

**Comment by kastiglione** [comment]
EDIT: I originally wrote `make build` but it's `make workspace` that's the problem.

**Comment by jerrymarino** [comment]
Hey @kastiglione - thanks for the report! It currently builds `TulsiGenerator` with Xcode in order to bundle the aspect, since that won't work with `SPM` Are you running Xcode 10 by any chance? I haven't tried _building_ XCHammer on Xcode 10 yet but it's on our immediate radar.

Generally, we bump Tulsi when an interesting change comes up or we need to make a fix to it, like all deps, it's pinned to a known working version. Prior to the `0.16.1` commit it's been pinned for quite a while. If [the XCHammer PR](https://github.com/bazelbuild/tulsi/pull/59) lands, it will be less effort to keep up to date.

**Comment by jerrymarino** [comment]
Hey @kastiglione is this something we can close out now? We made a few changes to the `Makefile` and Xcode developer workflow. Long term, we're aiming to remove the SPM build system in the `Makefile` and build XCHammer Xcode projects with XCHammer 😄

**Comment by kastiglione** [comment]
I don't think this is relevant anymore.
