### ISSUE TITLE
genrules causing XCHammer generate failure

### ISSUE THREAD

**Issue by kastiglione** [pinterest/xchammer#46]
There are three `genrule`s in our build. These do a bit of codegen, and localization setup. The `genrule`s look something like this:

```py
genrule(
    name=name + "NameSuffix",
    srcs=[...],
    cmd="$(location //tools:some_script) generate $< $@ " + name,
    outs=["FilePrefix+{}.swift".format(name)],
    tools=["//tools:some_script"],
)
```

These `genrule`s are called from macros of our own. The `name` refers to a module.

Running `XCHammer generate xchammer.yaml` gives the following errors:

```
swiftException(XCHammer.Generator.GenerateError.some(184 Spec validations errors:
    - Target "AppCoreUI" has a missing source directory "/Users/me/src/TheApp/Modules/AppCoreUI/AppCoreUIViewControllers.swift"
    - Target "AppCoreUI" has a missing source directory "/Users/me/src/TheApp/Modules/AppCoreUI/I18N+AppCoreUI.swift"
    - Target "AppCoreUIResources" has a missing source directory "/Users/me/src/TheApp/Modules/AppCoreUI/Localizable.strings"
```

Here you can see the `outs` of the `genrule`s are causing problems. Note also the strange `missing source directory`, not sure why these files are being called directories.

What more info can I provide?

**Comment by jerrymarino** [comment]
Hey @kastiglione! Thank you, kindly for the report.

The `184 Spec validations errors` are from `XcodeGen` - outputs from rules are incorrectly entered in the `ProjectSpec.Project`.

I'd suggest setting up an instance of the rule usage in the sample project. `genrule`s that simply copy a valid input file would be enough to reproduce, fix, and integration test going forward:
- `genrule` for a localized resource ( `.strings` )?  Localization is a special case
- `genrule` for a swift file.

With that, fixing should be pretty straight forward.

In addition to the bug, I suspect an error in that `XcodeGen` error message - if a file is not on disk, then it wouldn't be able to differentiate between a `directory` and a `source` 🤷‍♀️ .  It's confusing none the less.

**Comment by jerrymarino** [comment]
Several PRs were submitted to resolve the genfile issue in the best possible way. We don’t want to slow down generation, so:
    - XCHammer no longer requires source files during gen time. This is good for remote caching too.
    - The user optionally adds the tag `xchammer` to build things before Xcode build xcode targets. If 
       you only want to build with Bazel, this tag doesn't matter.

I believe the remaining issue to resolve this is around the target inclusion issue:
```
+++ b/Sources/XCHammer/XcodeTarget.swift
@@ -73,11 +73,13 @@ func includeTarget(_ xcodeTarget: XcodeTarget, pathPredicate: (String) -> Bool)
         return false
     }
-    if xcodeTarget.frameworkImports.count > 0 {
-        return false
-    }
+    // FIXME: Why is this here? This will break with `swift_library`
+    // if xcodeTarget.frameworkImports.count > 0 {
+    //    return false
+    //}
```

**Comment by rahul-malik** [comment]
Is the tag the best approach here? Would it be safe to assume we could just build any custom genrules that are target dependencies?

**Comment by kastiglione** [comment]
> Would it be safe to assume we could just build any custom genrules that are target dependencies?

I'm thinking it's not safe, because you don't know what its deps are. It might be the last thing to be built, depending on the world, in which case if you build it, you build everything.

**Comment by kastiglione** [comment]
@jerrymarino There were a number of changes, at the time we thought it was that `frameworkImports` check, but I have a different diff right now:

```diff
diff --git a/Sources/XCHammer/XcodeTarget.swift b/Sources/XCHammer/XcodeTarget.swift
index aa065d3..fc077aa 100644
--- a/Sources/XCHammer/XcodeTarget.swift
+++ b/Sources/XCHammer/XcodeTarget.swift
@@ -72,9 +72,9 @@ func includeTarget(_ xcodeTarget: XcodeTarget, pathPredicate: (String) -> Bool)
     guard let buildFilePath = xcodeTarget.buildFilePath else {
         return false
     }
-    guard pathPredicate(buildFilePath) else {
-        return false
-    }
+//    guard pathPredicate(buildFilePath) else {
+//        return false
+//    }
     if xcodeTarget.frameworkImports.count > 0 {
         return false
     }
@@ -416,6 +416,8 @@ guard let productType = extractProductType() else {
             return xcTargetName + ".xctest"
             case .AppExtension, .XPCService, .Watch1App, .Watch2App, .Watch1Extension, .Watch2Extension, .TVAppExtension:
             return xcTargetName + ".appex"
+            case .StaticLibrary:
+            return xcTargetName
             default:
             fatalError()
         }
```

**Comment by kastiglione** [comment]
I just debugged the `pathPredicate` and came up with this solution: #65.

**Comment by kastiglione** [comment]
This is resolved.
