### ISSUE TITLE
Add support for runtime environment variables in target config

### ISSUE THREAD

**Issue by SterlingWaves** [pinterest/xchammer#62]
Currently the `XCScheme` struct takes in the `commandLineArguments` for cli args but not the environment variables (key-value pairs). Would be great to have this support so we can pass in the env var pairs for each target in the XCHammer.yaml file under `targetConfig`

**Comment by jerrymarino** [comment]
Hey @SterlingWaves - thanks for filing issue. I totally agree that we should add this 👍 . Following the same pattern of `commandLineArguments`, we should be able to write env vars into the schemes.
